site_name: My MkDocs Material Documentation
site_url: https://draxfm.github.io/flux/
docs_dir: docs
use_directory_urls: true
theme:
  name: material
  icon:
    logo: simple/livechat
  features:
    - navigation.footer
  font:
    text: Merriweather Sans
  palette: 
    scheme: slate
    primary: indigo
    accent: indigo
  
markdown_extensions:
- attr_list
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences
- admonition
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js
  - https://unpkg.com/highlightjs-luau/dist/luau.min.js
  - javascripts/highlight-init.js  # your own init code


extra:
  social:
    - icon: simple/roblox
      link: https://www.roblox.com/de/users/1817341144/profile
    - icon: simple/github
      link: https://www.github.com/DraxFM