site_name: Flux Chat
site_url: https://draxfm.github.io/Flux/
docs_dir: docs
nav:
  - Home:
    - Introduction: index.md
    - Get Started: installation.md
    - Features: features.md
    - API: api.md
  - Bug Reporting: bug-reporting.md
theme:
  name: material
  icon:
    logo: simple/livechat
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.instant
  font:
    text: Inter
  palette: 
    scheme: slate
    primary: blue
    accent: green

extra_css:
  - styles/extra.css

  
markdown_extensions:
- attr_list
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences:
    custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- admonition
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js
  - https://unpkg.com/highlightjs-luau/dist/luau.min.js
  - javascripts/highlight-init.js  # your own init code


extra:
  social:
    - icon: simple/roblox
      link: https://www.roblox.com/users/1817341144/profile
    - icon: simple/github
      link: https://www.github.com/DraxFM